format base + eslint

diff --git a/.github/workflows/prettier.yml b/.github/workflows/prettier.yml
--- a/.github/workflows/prettier.yml
+++ b/.github/workflows/prettier.yml
@@ -27,11 +27,11 @@ jobs:
 
       - name: Prettify code
         run: |
-            yarn format
+          yarn format
 
       - name: Compare output
         run: |
-            if ! git diff-index --quiet HEAD --; then 
-              echo "This code is not linted properly. Marking job as failed..."
-              exit 1
-            fi
+          if ! git diff-index --quiet HEAD --; then 
+            echo "This code is not linted properly. Marking job as failed..."
+            exit 1
+          fi
